spring:
  application:
    name: JwtImplementation
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://localhost:3306/jwt_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
